version: "3"

services:
  db:
    image: postgres:9.6.2-alpine
    ports:
      - "$DB_PORT:5432"
    env_file: .env
  app:
    build: .
    links:
      - db
    working_dir: /app/src/
    env_file: .env
