version: "3"

services:
  db_test:
    image: postgres:9.6.2-alpine
    env_file: .env
  app:
    build: .
    links:
      - db_test
    working_dir: /app/src/
    command: python data.py
    env_file: .env
